[package]
name = "tur"
version = "0.10.0"
edition = "2021"
authors = ["greykaizen"]
description = "A download manager built smarter and more reliable. Reimagined from the ground up."
license = "Apache-2.0"
repository = "https://github.com/greykaizen/tur.git"
readme = "README.md"
default-run = "tur"

[lib]
name = "tur_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-store = "2"
tauri-plugin-deep-link = "2"
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bincode = { version = "2", features = ["derive", "serde"] }
reqwest = { version = "0.12", features = ["stream", "socks", "cookies", "brotli", "gzip", "native-tls-vendored"] }
url = "2"
tokio = { version = "1", features = ["signal", "macros"] }
futures-util = "0.3"
tokio-util = { version = "0.7" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rusqlite = "0.32"
uuid = { version = "1", features = ["v7", "serde"] }
anyhow = "1"
dirs = "5"
urlencoding = "2"
indicatif = "0.18.3"
chrono = { version = "0.4", features = ["serde"] }

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-single-instance = { version = "2", features = ["deep-link"] }
tauri-plugin-autostart = "2"

[dev-dependencies]
proptest = "1.9.0"
